---
- name: Nginx balanser deployment playbook
  hosts: nginxbalancerserver    # Inventory hosts group / server to act on
  become: yes               	# If to escalate privilege
  become_method: sudo       	# Set become method
  #remote_user: root         	# Update username for remote server
  
  vars:
    server1: 10.26.1.192:8080
    server2: 10.26.1.199:8080

  roles:
    - nginx
