---
- name: Tomcat deployment playbook
  hosts: webserver          # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: root         # Update username for remote server
  

  roles:
    - tomcat

