- name: Download prometheus
  get_url:
    url: "{{ prometheus_archive_url }}"
    dest: "{{ prometheus_archive_dest }}"

- name: Add "prometheus" group
  group:
    name: prometheus

- name: Add "prometheus" user
  user:
    name: prometheus
    group: prometheus
    system: yes

- name: Extract prometheus archive
  unarchive:
    src: "{{ prometheus_archive_dest }}"
    dest: /home/prometheus/
    owner: prometheus
    group: prometheus
    remote_src: yes
    creates: "{{ home_promet }}/prometheus"

#- name: COPY FILE BY SCRIPT
#  shell:
#    cmd: cp "{{ home_promet }}/prometheus" /usr/local/bin/

#- name: COPY FILE BY SCRIPT
#  shell:
#    cmd: cp "{{ home_promet }}/promtool" /usr/local/bin/

#- name: COPY FILE BY SCRIPT
#  shell:
#    cmd: cp -r {{ home_promet }}/consoles /etc/prometheus

#- name: COPY FILE BY SCRIPT
#  shell:
#    cmd: cp -r {{ home_promet }}/console_libraries /etc/prometheus/


#- name: copy prometheus files
#  file:
#    src: "{{ home_promet }}/prometheus"
#    dest: /usr/local/bin/
#    owner: prometheus
#    group: prometheus
#    state: hard

#- name: copy prometheus files
#  file:
#    src: "{{ home_promet }}/promtool"
#    dest: /usr/local/bin/
#    owner: prometheus
#    group: prometheus
#    state: hard

#- name: copy prometheus files
#  file:
#    src: "{{ home_promet }}/consoles"
#    dest: /etc/prometheus/
#    owner: prometheus
#    group: prometheus
#    recurse: yes
#    state: directory

#- name: copy prometheus files
#  file:
#    src: "{{ home_promet }}/console_libraries"
#    dest: /etc/prometheus/
#    owner: prometheus
#    group: prometheus
#    recurse: yes
#    state: directory


############
- name: Copy prometheus service file
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Open 9090 port on the firewall by prometheus
  firewalld:
    port: 9090/tcp
    permanent: true
    state: enabled

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

#- name: Start and enable prometheus
#  service:
#    daemon_reload: yes
#    name: prometheus
#    state: started
#    enabled: yes

- name: START BY SHELL
  shell: 
    cmd: "{{home_promet}} &"
