- name: Run my script to configure
  script: somescript.sh

- name: Install rsync policy
  dnf:
    name: policycoreutils-python-utils
    state: present

- name: Change the syslogd_t
  selinux_permissive:
    name: syslogd_t
    permissive: true

- name: Set time zone
  timezone:
    name: Europe/Kiev

<<<<<<< HEAD
#- name: Download setup linux script
#  get_url:
#    url: "{{ setup_linux_url }}"
#    dest: "{{ setup_linux_dest }}"
=======
# - name: Download setup linux script
#   get_url:
#     url: "{{ setup_linux_url }}"
#     dest: "{{ setup_linux_dest }}"
>>>>>>> 58b6ee147992b04967f1d1f8541f2e0f2f9d8e7f

#- name: Download setup linux script by script
#  script: "curl -sS -O http://{{ nagioslogserver }}/nagioslogserver/scripts/setup-linux.sh"

- name: Copy setup linux script
  copy:
    src: setup-linux.sh
    dest: "{{ setup_linux_dest }}"

- name: Open tomcat port on the firewall
  firewalld:
    port: 5544/tcp
    permanent: true
    state: enabled

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

#- name: Run Script
#  script: "{{ setup_linux_dest }}/setup-linux.sh -s {{ nagioslogserver }} -p 5544 -f {{ tomcat_catalina_log }} -t tomcat_logs"
